name: A workflow for my Hello World file
on: push
env:
  GREETING: 'Mona'
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{env.GREETING}}
  notify:
    name: Send SMS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+16308127495'
          toPhoneNumber: '+436642040403'
          message: 'Success greeting ${{env.GREETING}}'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
